#!/bin/sh
#
# stage.sh - assemble the non-binary package contents (generated
# configuration, systemd units and compressed manual pages) under
# packages/nfpm/stage/, which packages/nfpm/nfpm.yaml and the nfpms
# section of .goreleaser.yaml both read from.
#
# The configuration samples and units are generated by make from their
# .in templates with the package paths (prefix=/usr, sysconfdir=/etc);
# see PKG_MAKEVARS in packages/release.mk, which is the canonical
# definition. This script is run by "make pkg-stage" (with PKG_MAKEVARS
# exported) and by the goreleaser before hook (with the defaults below).
#
# Usage: sh packages/nfpm/stage.sh [stage-dir]

set -eu

top=$(cd "$(dirname "$0")/../.." && pwd)
stage=${1:-$top/packages/nfpm/stage}
MAKE=${MAKE:-make}

# Same values as PKG_MAKEVARS in packages/release.mk and the RPM spec:
# state under /var/lib/greyd, pidfiles under /var/empty.
PKG_MAKEVARS=${PKG_MAKEVARS:-"prefix=/usr sysconfdir=/etc localstatedir=/var/lib \
    unitdir=/usr/lib/systemd/system DEFAULT_CONFIG=/etc/greyd/greyd.conf \
    GREYD_PIDFILE=/var/empty/greyd/greyd.pid \
    GREYLOGD_PIDFILE=/var/empty/greylogd/greylogd.pid"}

cd "$top"

# The generated files are gitignored and dependency based; -B forces
# them to be regenerated with the package paths whatever is lying around.
# shellcheck disable=SC2086
$MAKE -B conf $PKG_MAKEVARS >/dev/null

rm -rf "$stage"
mkdir -p "$stage/etc" "$stage/systemd" "$stage/man/man8" "$stage/man/man5" "$stage/doc"

for f in etc/greyd.conf etc/greyd.docker.conf etc/greyd.redhat-init \
         etc/greylogd.redhat-init etc/greyd.debian-init etc/greylogd.debian-init; do
    cp "$f" "$stage/etc/"
done

# Every generated unit (the .in templates stay behind); a pattern with
# no match is skipped.
for f in packages/systemd/*.service packages/systemd/*.timer packages/systemd/*.socket; do
    [ -f "$f" ] && cp "$f" "$stage/systemd/"
done

# gzip -n omits the timestamp so the archives are reproducible.
for f in doc/*.8; do
    gzip -9n -c "$f" > "$stage/man/man8/$(basename "$f").gz"
done
for f in doc/*.5; do
    gzip -9n -c "$f" > "$stage/man/man5/$(basename "$f").gz"
done

cp README.md COPYING AUTHORS NEWS ChangeLog "$stage/doc/"
cp adapters/db/mysql/mysql_schema.sql adapters/db/postgresql/postgresql_schema.sql "$stage/doc/"

echo "staged package contents in $stage"
